name: CI

on:
  pull_request:
    branches: [ main, staging, staging-ci ]

jobs:
  lint_client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hamza-client
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.x'
      - name: Install Client Dependencies
        run: yarn install
      - name: Lint Client
        run: yarn lint

  build_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hamza-server
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.x'
      - name: Install Server Dependencies
        run: yarn install
      - name: Build Server
        run: yarn build


  build_client:
    needs: [lint_client, build_server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.x'
      - name: Install Client Dependencies (if not cached)
        run: yarn install
      - name: Start Server
        run: |
          cd hamza-server
          yarn start &
          - name: Build Client
          run: yarn build
