name: CI

on:
  pull_request:
    branches: [main, staging, staging-ci]

jobs:

  lint_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install Dependencies for Client
        run: yarn install
        working-directory: hamza-client
      - name: Lint Client
        run: yarn lint
        working-directory: hamza-client
