build_and_test:
  needs: install_dependencies
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.18.x
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.x'
    - name: Cache node_modules for hamza-client
      uses: actions/cache@v2
      with:
        path: hamza-client/node_modules
        key: ${{ runner.os }}-hamza-client-${{ hashFiles('hamza-client/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-hamza-client-
    - name: Cache node_modules for hamza-server
      uses: actions/cache@v2
      with:
        path: hamza-server/node_modules
        key: ${{ runner.os }}-hamza-server-${{ hashFiles('hamza-server/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-hamza-server-
    - name: Build Server
      run: yarn build
      working-directory: hamza-server
    - name: Lint Client
      run: yarn lint
      working-directory: hamza-client
