name: Docker postgres CI

on:
  push:
    branches-ignore: [ ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: postgres:latest
          outputs: type=docker,dest=/tmp/postgres.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: postgres
          path: /tmp/postgres.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: postgres
          path: /tmp
      - name: Load postgres
        run: |
          docker load --input /tmp/postgres.tar
          docker image ls -a 
